spring.application.name=petapi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/db_apipet
spring.datasource.username=root
spring.datasource.password=