spring.application.name=aulasecurity

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/db_aula20260428
spring.datasource.username=root
spring.datasource.password=
