spring.application.name=ativsecurity

# 1. URL de conex�o (troque 'nome_do_banco' pelo nome que voc� criou no MySQL)
spring.datasource.url=jdbc:mysql://localhost:3307/db_security?createDatabaseIfNotExist=true

# 2. Credenciais
spring.datasource.username=root
spring.datasource.password=root

# 3. Driver e Dialeto (ajuda o Hibernate a n�o se perder)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 4. Cria as tabelas automaticamente para voc�
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.docker.compose.enabled=false


