spring.application.name=ativ20260505

# 1. URL de conexão (troque 'nome_do_banco' pelo nome que você criou no MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/db_ativ260505?createDatabaseIfNotExist=true

# 2. Credenciais
spring.datasource.username=root
spring.datasource.password=

# 3. Driver e Dialeto (ajuda o Hibernate a não se perder)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 4. Cria as tabelas automaticamente para você
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true